networks:
  inventory-network:
    driver: bridge 

services:
  inventory-api:
    build:
      context: ./
      dockerfile: ./src/InventoryMicroservice.Api/Dockerfile
    networks:
      - inventory-network
    ports:
      - "53080:8080"
    environment:
      - SQL_CONNECTION_STRING=Data Source=inventory-sqlserver;Integrated Security=false;User ID=sa;Password=@someThingComplicated1234;Encrypt=false;TrustServerCertificate=true;
      - DATABASE_NAME=InventoryDatabase
      - SHOULD_SETUP_DATABASE=true
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=Password123!
      - RABBITMQ_HOST=rabbit-mq
      - RABBITMQ_PORT=5672
      - SHOULD_SHOW_SWAGGER=true
    restart: unless-stopped
    depends_on:
      - rabbit-mq
      - inventory-sqlserver

  rabbit-mq:
    image: rabbitmq:4-management
    networks:
      - inventory-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "15672:15672"
      - "5671:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Password123!

  inventory-sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "yourStrong(!)Password", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "1433:1433"
    networks:
      - inventory-network
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    restart: unless-stopped

